[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "nlhe-sim"
version = "0.1.0"
description = "NLHE poker simulator"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["."]
